import numpy as np
arr1 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2 = np.array([[3, 4, 5],[6, 7, 8],[8, 5, 3]])
print("3-D matrix")
print(arr1)
print(arr2)
print("mutliplied product of two matrix")
x = np.multiply(arr1,arr2)
print(x)
print("Addition of two matrix")
y = np.add(arr1,arr2)
print(y)
print("substraction of two matrix")
z = np.subtract(arr1,arr2)
print(z)
